### ISSUE TITLE
Consider adding config option that disables frequent calls to stat when listing collections

### ISSUE THREAD

**Issue by korydraughn** [irods/irods_client_nfsrods#109]
The code below is one reason for the slow performance of listing the contents of a collection with many entries.
https://github.com/irods/irods_client_nfsrods/blob/3de13450e8cd2f2a2b208266ec5937a9296b327d/irods-vfs-impl/src/main/java/org/irods/nfsrods/vfs/IRODSVirtualFileSystem.java#L863-L871

**Comment by korydraughn** [comment]
Given the conversation at #112 and #51, it has been decided that the stat call referenced in this issue is unnecessary and will be removed.

**Comment by trel** [comment]
closed via https://github.com/irods/irods_client_nfsrods/pull/116
