### ISSUE TITLE
Directory listing hangs 

### ISSUE THREAD

**Issue by ac55-sanger** [irods/irods_client_nfsrods#110]
Hi, 

We have been seeing this issue with our NFSRODs integrations with iRODS where a listing of mounted directory hangs for an arbitrary amount of time in two cases:

1. irods collection has a large number of files (65369)
- We have a Jbrowse2 (ngnix) web app which is used to list the mounted directory content on a web page. And once that's been used, the directory listing on the terminal hangs every time. (easily reproducible)

2. Any other subdirectory of the mounted directory 
- This is indeed random and we have seen it only 2-3 times till now.

There are no errors in NFSRODs logs.

**System information:**
1. Running irods nfsrods service:
m2.large, 93 GB RAM, 8 CPU,  Ubuntu 18.04.5 LTS
2. Mounted on:
o2.2xlarge, 43.4 GB RAM, 30 CPU, Ubuntu 18.04.5 LTS

**NFSRODs info:**
#docker run --rm nfsrods sha
Build Time    => 2020-07-01T15:00:57+0000
Build Version => 1.0.0
Build SHA     => 5aecafa369a2f4bcf56ff68707817d9a7ec96aa0

Could this please be looked at as it's been a blocker for us?
Thanks

**Comment by trel** [comment]
We have reproduced this - the numerous stat() calls were... numerous.   Thinking through a solution...

**Comment by ac55-sanger** [comment]
That's good to know. Thanks @trel
