### ISSUE TITLE
Does not run without /dev/stdin binded to docker

### ISSUE THREAD

**Issue by peterverraedt** [irods/irods_client_nfsrods#125]
Commit 318663d3a06f7d9aedfb49c470ecdf84d7e76ad6 makes running the docker image without the `-i` flag crash immediately, as /dev/stdin is absent. This makes a container workflow completely useless.

**Comment by korydraughn** [comment]
Yes, 2.0 requires the `-i` flag. Is the use of this flag causing issues? Can you provide more info about your use-case?

**Comment by peterverraedt** [comment]
We run nfsrods next to our irods container setup in a Hashicorp nomad cloud server setup. There, containers are started noninteractively, just as any Kubernetes/docker swarm/... setup would do. A container is expected to run until an explicit SIGTERM/SIGINT signal to its main process.

**Comment by korydraughn** [comment]
Are you saying the containers cannot be started with the `-i` flag in your environment? If so, is that due to security reasons or are the tools used to launch the containers enforcing the non-interactive mode?

**Comment by peterverraedt** [comment]
Yes, the tools launching the containers enforce to run the containers non-interactively. For non-interactive setups, /dev/stdin is of course not provided to the container.

I'm currently fixing by putting `sleep infinity | java ...` in `start.sh`.

**Comment by korydraughn** [comment]
Gotcha. We'll adjust NFSRODS to run without the `-i` flag.
