### ISSUE TITLE
NFSRODS needs a way to select the same replica for parallel writes

### ISSUE THREAD

**Issue by korydraughn** [irods/irods_client_nfsrods#126]
NFSRODS needs to provide options for specifying which replica to target in a multi-replica case. This is required due to iRODS growing support for data object locks, replica access tokens, and parallel transfer across port 1247.

When a replica is opened for writing in iRODS v4.2.9, it enters the *intermediate* state. This state will cause any attempts to open the data object to fail. However, if a replica access token is provided and the same replica is targeted, the next call to open will succeed. This enables clients to write to the same replica in parallel.

This is exactly the problem behind issue #124. NFSRODS does not have support for parallel transfer, hence it does not know anything about locking or replica access tokens. Even if NFSRODS did have these capabilities, there would still be one problem...

How does NFSRODS select the same replica for each stream?

What criteria should NFSRODS use when selecting a replica to open?
Should that criteria be configurable?

Keep in mind that the user communicating with NFSRODS does not have any options for targeting a specific replica.

**Comment by trel** [comment]
Some initial thoughts...

1. NFSRODS gains a configuration option that describes a 'heuristic'... aka 'highest replica number', 'oldest good replica', or 'latest good replica'... and then has to have the algorithm written to satisfy that heuristic.  This could include roundtrips to the catalog to find/determine the correct replica number for all concurrent calls to `open()`.
2. Without requesting a particular replica on initial `open()`, aka the server decides... NFSRODS gets from the server the replica number that was just opened, and can use that information for all subsequent sibling parallel `open()` calls.  Does the server already communicate that information?  Would that be a change in the server reply?

Either we ask first, or we are told.  Are there other options?

**Comment by korydraughn** [comment]
This can be closed.

**Comment by trel** [comment]
sold.

**Comment by trel** [comment]
current work can be found in https://github.com/irods/irods_client_nfsrods/pull/129 

should be merged before too long, will be in the next release.
