### ISSUE TITLE
Investigate PAM authentication

### ISSUE THREAD

**Issue by korydraughn** [irods/irods_client_nfsrods#14]

**Comment by korydraughn** [comment]
Due to the new security model, can this be closed or does it need further investigation?

**Comment by trel** [comment]
NFSRODS needs to use PAM auth (handled by Jargon) to connect with the iRODS server.

I don't think this is done at this time.

**Comment by trel** [comment]
NFSRODS trusts the uid coming through the mountpoint - there is no auth to be done by NFSRODS.
