### ISSUE TITLE
iRODS timestamps do not provide enough precision to detect changes

### ISSUE THREAD

**Issue by korydraughn** [irods/irods_client_nfsrods#154]
## Bug Report
It is possible for NFSRODS to present incorrect information when operations are executed very quickly.

NFS detects changes in the filesystem via the mtime. iRODS stores timestamps in seconds. Systems depending on these timestamps will not operate correctly if operations complete within the same second.

The following operations are known to be affected:
- [x] unlink
- [x] list
- [x] rename/move
- [x] copy
- [x] write

### Solution
To get around this, NFSRODS must manually clear caches on completion of these operations.

**Comment by trel** [comment]
nice.    consider some checkboxes in case you don't get them all in one go.
