### ISSUE TITLE
Building nfsrods in an automation fails

### ISSUE THREAD

**Issue by jbeal-work** [irods/irods_client_nfsrods#169]
Atleast the way I am implementing it at Sanger ( in a gitlab-ci pipeline ) which uses docker in docker.

I will make a pull request for deleting the three character fix.

**Comment by trel** [comment]
Can you share the failure text?

**Comment by jbeal-work** [comment]
So in the automation I have today:

`cat build_jar.sh | sed -e 's/-it//' | bash`
