### ISSUE TITLE
SNAPSHOT reference in 2.1.0 pom

### ISSUE THREAD

**Issue by DukeVimes** [irods/irods_client_nfsrods#177]
in tagged version 2.1.0 the pom contains a reference to 4.3.2.5-SNAPSHOT of Jargon.
Shouldn't tagged versions always reference RELEASE?

**Comment by trel** [comment]
That is the intent - but 4.3.2.5-RELEASE was not available at the time.    If this is important for your organization / policy, please let us know and we can prioritize accordingly.

**Comment by korydraughn** [comment]
Yes, using SNAPSHOTs is not our preference, however, they are okay as long as they don't lead to security vulnerabilities.

The next release of NFSRODS will use 4.3.3.0-RELEASE.

Closing.
