### ISSUE TITLE
Multi-owned collections and data objects are not accessible

### ISSUE THREAD

**Issue by korydraughn** [irods/irods_client_nfsrods#18]
Given two users, **alice** and **bob**.

**alice** gives **own** permissions on a collection to **bob**.
```bash
ichmod own bob /tempZone/home/alice/shared
```
Now **bob** can use `iput` to put files into the collection shared by **alice**. However, if **bob** tries to put a file, via an NFSRODS mount, into the collection shared by **alice**, then NFSRODS stops it and causes a permission error to be printed to the console.

Due to the linux permissions model, sharing collections and data objects is not possible without allowing all users some access to all collections in the path.

**Comment by michael-conway** [comment]
is this an issue of throwing an exception or getting a data not found down in jargon? Or does NFSRODS bop down the tree from /tempZone and is getting tripped up by strict acls?

**Comment by korydraughn** [comment]
NFSRODS is inspecting each path element starting at /tempZone and getting tripped up because the iRODS account doesn't have permission to see a collection leading up to the target collection or data object.

**Comment by michael-conway** [comment]
And iput does not descend the tree, it goes right to the given absolute path. I wonder if it would be possible to use a proxy user for this part of the operation?

**Comment by korydraughn** [comment]
Yes.  The proxy account in NFSRODS is a rodsadmin account and would work. I'm concerned about having to reimplement logic that is already in iRODS if the proxy account is used.

**Comment by korydraughn** [comment]
This has been solved by making all directories (collections) executable in NFSRODS.
