### ISSUE TITLE
Setting permissions for unknown users breaks NFSRODS ACL support

### ISSUE THREAD

**Issue by korydraughn** [irods/irods_client_nfsrods#24]
If `nfs4_setfacl` is used to modify permissions for a user that does not exist in the OS and iRODS, NFSRODS will delete all permissions and will not be able to recover.

Fixing the permissions from the client-side does not appear to be possible due to the fact that NFSRODS caches ACL information.

Fixing the permissions from the server-side is possible, but NFSRODS will not detect the changes.

The only known solution is to restart the NFSRODS server and remount it.

**Comment by michael-conway** [comment]
is there a way to intercept this in our impl and pre-check/ignore in order
to prevent this?

**Comment by trel** [comment]
We should be able to catch this scenario.

If we can do it without pre-checking, that'd be great... just keep the current permissions in memory... try the setfacl, if it fails for this reason, roll it back and tell the client it didn't go through.
