### ISSUE TITLE
add expected 'df' output to README

### ISSUE THREAD

**Issue by trel** [irods/irods_client_nfsrods#25]
NFSRODS populates the available and used space fields as `0`.   This signals to a default `df` request to ignore the mountpoint information for NFSRODS.

Live NFSRODS mountpoint information can be viewed via `df -a`.

**Comment by michael-conway** [comment]
What's the best approach to giving a meaningful number? Or is this about
setting a non-zero value?

**Comment by trel** [comment]
We've settled on reporting zeroes for now since anything else would be misleading.

- There is no 'actual' number (iRODS has multiple resources, possibly including AWS S3...).
- Arbitrary 'ReallyBigNumber' is misleading and could cause certain problems to other programs using that information to make decisions.
- Zero is a known pattern for other 'silent' mountpoints.

If there are good ideas, please share - otherwise, we're going with `0` for now.

**Comment by anderbubble** [comment]
We're working on deploying quota support as seen here:

https://github.com/irods/irods_policy_examples/blob/master/irods_policy_logical_quotas.re

I'd love to have these quotas reflected in the df output. Maybe there should just be a standard set of irods metadata that should get reported out via NFSRODS? Or maybe it should read df data out of a PEP? (Sorry if these are the wrong terms; let me know if this isn't clear.)

**Comment by michael-conway** [comment]
It would not be terribly difficult to service avus or add api support for
quotas gen there was a definite standard way in irods? I did t know what
the current state of quotas was.

**Comment by anderbubble** [comment]
To be fair, I think the current state is "nonexistent" except that we asked for it and that policy is what came out. :) We haven't deployed or tested it yet; but that's basically my next step for our environment (in competition with "get NFSRODS to work").

**Comment by trel** [comment]
The linked logical quotas policy is for 'all users' under a particular logical path.  It handles keeping track of totals in the system via pre- and post- PEPs when data is added/removed from the system. 
 They possibly could be represented to `df` in the way you're describing - however...

iRODS also has the concept of both total and per-resource quotas as defined per-user and per-group.   I can't figure out how to represent those to `df` at this time - or whether they get in the way at all.

Also, NFSRODS is only a single iRODS client - so we'd need to think through what representing 'capacity' means for other clients and how they can be fairly informed of the same type of information.
