### ISSUE TITLE
add log_level configuration

### ISSUE THREAD

**Issue by trel** [irods/irods_client_nfsrods#26]
- default should be INFO for now, but probably WARNING for 1.0.0
- allow override with environment variable (NFSRODS_LOG_LEVEL?)

**Comment by michael-conway** [comment]
Definitely consider adding log level as a parameter. I'd even suggest
looking at JMX MBean access for real time stats and tuning, especially
think about more dynamic performance/pool/cache tuning?

**Comment by korydraughn** [comment]
Is this really needed? The log4j config file is already exposed. Because log4j 2 is used now, any changes to the config file are picked up within 5 seconds.

**Comment by michael-conway** [comment]
it depends on how much we want to expose tuning. It can def go later but we're already doing this with Jargon tuning params, exposing JargonProperties as a JMX bean. This might indeed be useful in a phase where we are doing performance optimization? E.g. if we do get into streaming improvements.

**Comment by trel** [comment]
Closing this - it's covered by the log4j properties and the connection pooling issue is #74.
