### ISSUE TITLE
Failed to register at portmap: portmap service not available

### ISSUE THREAD

**Issue by anderbubble** [irods/irods_client_nfsrods#48]
```
Sep 30 22:28:43 irods1.rc.int.colorado.edu docker[12731]: 2019-10-01 04:28:43.973 WARN  Thread-1 [OncRpcSvc] - Failed to register at portmap: portmap service not available
```

If NFSRODS is not meant to be able to register at portmap in the container, then it should be configured to not attempt to register at portmap. Otherwise, this WARN is noise that might lead an admin to believe something is wrong.

**Comment by trel** [comment]
Do we just remove this line?

https://github.com/irods/irods_client_nfsrods/blob/157525561b27d39cdb410f9d295923148d56e5ff/irods-vfs-impl/src/main/java/org/irods/nfsrods/vfs/ServerMain.java#L80

**Comment by anderbubble** [comment]
It should probably remain, but configurable, and possibly default off.

**Comment by korydraughn** [comment]
this may have been resolved.  is anyone still seeing this message following recent releases?

**Comment by trel** [comment]
I thought I had seen it with 1.0.0... do you not?

**Comment by korydraughn** [comment]
it didn't show up in my last test of nfsrods.  i need to verify that though.

**Comment by trel** [comment]
confirmed with `irods/nfsrods:1.0.0` as released...
```
2020-08-26 14:15:25.718 WARN  Thread-1 [OncRpcSvc] - Failed to register at portmap: portmap service not available
```

**Comment by korydraughn** [comment]
Installing the `rpcbind` service and starting it fixes this issue. Fix coming in PR #114

**Comment by MartinGrignard** [comment]
Hi :wave:

We are trying to deploy this NFS client on our iRODS zone (currently my local test environment). All our services run in Docker containers, so I tried to run the Docker image as explained in the `README.md`.

When I start the container, here are the logs:

```
2024-04-09 13:27:24.965 INFO  Thread-1 [ServerMain] - Build Time    => 2024-04-09T07:45:07+0000
2024-04-09 13:27:24.965 INFO  Thread-1 [ServerMain] - Build Version => 2.2.0
2024-04-09 13:27:24.965 INFO  Thread-1 [ServerMain] - Build SHA     => 22028f190639e298c17a804df2a370bbb32b76e9
2024-04-09 13:27:25.134 INFO  Thread-1 [ServerMain] - main - Server config ==> {
  "nfs_server" : {
    "port" : 2049,
    "irods_mount_point" : "/testZone",
    "user_information_refresh_time_in_milliseconds" : 3600000,
    "file_information_refresh_time_in_milliseconds" : 1000,
    "user_access_refresh_time_in_milliseconds" : 1000,
    "object_type_refresh_time_in_milliseconds" : 300000,
    "user_permissions_refresh_time_in_milliseconds" : 300000,
    "user_type_refresh_time_in_milliseconds" : 300000,
    "list_operation_query_results_refresh_time_in_milliseconds" : 30000,
    "allow_overwrite_of_existing_files" : true,
    "using_oracle_database" : false
  },
  "irods_client" : {
    "host" : "provider.irods.local",
    "port" : 1247,
    "zone" : "testZone",
    "default_resource" : "backupResc",
    "ssl_negotiation_policy" : "CS_NEG_DONT_CARE",
    "connection_timeout_in_seconds" : 600,
    "proxy_admin_account" : {
      "username" : "rods",
      "password" : "*************"
    }
  }
}
2024-04-09 13:27:25.162 DEBUG Thread-1 [ServerMain] - configureClientServerNegotiationPolicy - Policy = CS_NEG_DONT_CARE
2024-04-09 13:27:25.316 DEBUG Thread-1 [IRODSIdMapper] - IRODSUser - iRODS mount point = /testZone
2024-04-09 13:27:25.316 DEBUG Thread-1 [IRODSIdMapper] - IRODSUser - Creating proxy for username [rods] ...
2024-04-09 13:27:25.671 DEBUG Thread-1 [IRODSIdMapper] - InodeToPathMapper - iRODS mount point = /testZone
2024-04-09 13:27:25.868 DEBUG Thread-1 [IRODSIdMapper] - establishRoot - Mapping root to [irods://rods@provider.irods.local:1247/testZone] ...
2024-04-09 13:27:25.869 DEBUG Thread-1 [IRODSIdMapper] - map - mapping inode number to path [10004 => /testZone] ...
2024-04-09 13:27:25.869 DEBUG Thread-1 [IRODSIdMapper] - map - previously mapped path [null]
2024-04-09 13:27:25.870 DEBUG Thread-1 [IRODSIdMapper] - establishRoot - Mapping successful.
2024-04-09 13:27:34.142 WARN  Thread-1 [OncRpcSvc] - Failed to register at portmap: portmap service not available
2024-04-09 13:27:34.144 INFO  Thread-1 [ServerMain] - main - Press ctrl-c to shutdown.
```

After searching for a bit, I found the present issue and [this commit](https://github.com/irods/irods_client_nfsrods/commit/2c28606f7972826e7dcd2a43e8ab985decf8e4aa). It seems that the modifications from this commit are not in the current repository.

I thus proceeded to add `rpcbind` to the list of the installed packages in the image, and `service rpcbind start` to the `start.sh` script. Then, the only difference in the logs are those two lines at the beginning:

```
ln: failed to create symbolic link '/run/sendsigs.omit.d/rpcbind': No such file or directory
Starting RPC port mapper daemon: rpcbind failed!
```

When I try to mount on another host/container using:

```
$ mkdir /irods
$ mount -v -o sec=sys,port=2049,nolock nfs.irods.local:/ /irods
mount.nfs: timeout set for Tue Apr  9 14:09:19 2024
mount.nfs: trying text-based options 'sec=sys,port=2049,nolock,vers=4.2,addr=172.20.0.4,clientaddr=172.20.0.5'
mount.nfs: mount(2): Operation not permitted
mount.nfs: trying text-based options 'sec=sys,port=2049,nolock,addr=172.20.0.4'
mount.nfs: prog 100003, trying vers=3, prot=6
mount.nfs: portmap query retrying: RPC: Unable to receive
mount.nfs: prog 100003, trying vers=3, prot=17
mount.nfs: portmap query failed: RPC: Unable to receive - Connection refused
mount.nfs: Operation not permitted
```

Do you have any idea why this does not work? Is there a reason why these lines are not included in the sources anymore?

**Comment by korydraughn** [comment]
The reason the changes in that commit for rpcbind aren't included is because of #155.

We bumped the OS image to Ubuntu 22.04 for NFSRODS v2.2.0. In all of my testing, the message about portmap never appeared to affect NFSRODS' operation.

We aren't sure what causes that message yet. For now, it has remained a low priority item since there's no evidence of it having a negative impact on usage.

As for the mount error, please explain your setup between computers, containers, and where the mount command is being run.

**Comment by MartinGrignard** [comment]
Thanks for the link to #155. Since it evicted NFSRODS from the list of the suspects for the mounting error, I investigated other mounts inside containers.

It turns out [mounting from within a container requires additional privileges](https://www.baeldung.com/linux/docker-mount-nfs-shares#mounting-directly-inside-the-container). Adding the `--privileged` flag when running the test container solved the mounting issue.

Sorry for bringing this issue back to life.

**Comment by korydraughn** [comment]
Glad you got it working.
