### ISSUE TITLE
Inaccessible objects should not be listed by "ls"

### ISSUE THREAD

**Issue by korydraughn** [irods/irods_client_nfsrods#51]
Users should only be able to list objects they have access to.

**Comment by michael-conway** [comment]
the listings are via GenQuery...so it would match the behavior of GenQuery. Seems like having an option for performance reasons with documentation, and you could default to doing the stat with the option of turning it off would be desirable? Are objects leaking in GenQuery and is that not the real issue?

**Comment by korydraughn** [comment]
I believe GenQuery is doing the right thing and the stat is unnecessary. See my comments at #112
