### ISSUE TITLE
implement SSL to iRODS

### ISSUE THREAD

**Issue by trel** [irods/irods_client_nfsrods#56]

**Comment by michael-conway** [comment]
? I don't really think there's much needed. If a cert is loaded in the docker image it will connect. There is a method to manipulate jargon properties in code that Kory knows if we wanted to add a special env variable or property flag for the docker container, then it should operate as expected.

**Comment by trel** [comment]
Right - this is just about building out the NFSRODS wiring and instructions for humans to get it working.

**Comment by trel** [comment]
Done!    NFSRODS now supports SSL connections to iRODS.
