### ISSUE TITLE
NFSRODS should support user and group auto-creation

### ISSUE THREAD

**Issue by anderbubble** [irods/irods_client_nfsrods#63]
When using nfs4_setfacl to set permissions for a user and/or group that exists locally, but not in iRODS, NFSRODS should support the ability to automatically create these users and groups in iRODS to properly reflect the intended permissions as mapped from upstream.

**Comment by trel** [comment]
Hmmm, no iRODS passwords... I think that would be okay...

I'm thinking this feature should be controlled by a boolean(?) setting in the `irods_client` section of the NFSRODS `server.json` configuration...  And probably off by 'default':

```
    "irods_client": {
        "create_rodsuser_account_if_missing": false,
```
or
```
        "auto_create_irods_users_and_groups": false,
```

If we can think of modes other than true/false... then we should make it an enum?...

Possibly...
- "off" / "rodsuser" / "rodsadmin" (really bad idea)
- "off" / "users_and_groups" / "users_only" / "groups_only"

**Comment by trel** [comment]
Feeling less and less like this should be happening 'out here'...  almost too much magic.

Leaving this open for now - but considering closing as a "won't implement".

**Comment by anderbubble** [comment]
I actually think I agree at this point. What I probably want is just a simple shell script around iadmin or similar that replicates a local account in iRODS. And that wouldn't require anything special (and I wouldn't expect it to come from upstream).

Feel free to close if you'd only keep it open for me. :)

**Comment by trel** [comment]
When you say 'replicates a local account'... you mean... sniffing/scanning local configuration/setup/accounts and then making/creating similar things (users/groups/permissions) exist over in the iRODS namespace...

An `iadmin` wrapper with marching orders.

Agreed, that should come from out here and doesn't sound like it would need any new functionality in the iCommands or NFSRODS or the iRODS server.

Thanks!

**Comment by anderbubble** [comment]
> When you say 'replicates a local account'... you mean... sniffing/scanning local configuration/setup/accounts and then making/creating similar things (users/groups/permissions) exist over in the iRODS namespace...

I really just mean using nss (e.g., a script that uses `getent passwd` and `getent group`) to get users and groups (probably only those specified) and replicates the users and groups in iRODS using `iadmin`. Nothing too complicated.

But, like I said, I don't expect this to be baked into irods proper. Just musing about how this could be more simply done without upstream changes.
