### ISSUE TITLE
public access collections not showing up during ls

### ISSUE THREAD

**Issue by anderbubble** [irods/irods_client_nfsrods#65]
I ran the following series of `ichmod` to grant public read access to some top-level directories

```
ichmod -M read public /
ichmod -M read public /curcZone
ichmod -M read public /curcZone/pl
ichmod -M read public /curcZone/pl/archive
```

This collection contains other sub-collections

```
[root@irods1 ~]# ils /curcZone/pl/archive | sed 's,archive/.*,archive/[redacted],'
/curcZone/pl/archive:
  C- /curcZone/pl/archive/[redacted]
  C- /curcZone/pl/archive/[redacted]
  C- /curcZone/pl/archive/[redacted]
  C- /curcZone/pl/archive/[redacted]
  C- /curcZone/pl/archive/[redacted]
  C- /curcZone/pl/archive/[redacted]
  C- /curcZone/pl/archive/[redacted]
  C- /curcZone/pl/archive/[redacted]
  C- /curcZone/pl/archive/[redacted]
  C- /curcZone/pl/archive/[redacted]
  C- /curcZone/pl/archive/[redacted]
  C- /curcZone/pl/archive/[redacted]
  C- /curcZone/pl/archive/[redacted]
  C- /curcZone/pl/archive/[redacted]
  C- /curcZone/pl/archive/[redacted]
  C- /curcZone/pl/archive/[redacted]
```

but when I `ls` this with NFSRODS there are no directories shown.

```
[root@irods1 ~]# sudo -u joan5896 ls /mnt/nfsrods/pl/archive
[root@irods1 ~]#
```

The behavior does not change if I re-mount NFSRODS.

**Comment by anderbubble** [comment]
NFSRODS log output: [Terminal Saved Output.txt](https://github.com/irods/irods_client_nfsrods/files/3923816/Terminal.Saved.Output.txt)

**Comment by trel** [comment]
`ichmod` has a `-r  recursive` option...

Can you try that?

**Comment by trel** [comment]
Also note the 'Inheritance' behavior of the ACLs... For when new collections appear down there later.

**Comment by anderbubble** [comment]
I don't want to apply the permission recursively. I want anyone to be able to see that the sub-collections under `/curcZone/pl/archive/` exist, but then I want to use per-allocation groups to grant permissions to each collection under that. As such, I'm expecting public read on `/curcZone/pl/archive/` to allow anyone to `ls /curcZone/pl/archive/` and get the list of immediate sub-collections, but the public doesn't necessarily have access to data in these sub-collections.

For the record: I also granted public to one of the sub-collections, and it doesn't show up, either.

**Comment by korydraughn** [comment]
I've verified that the reported behavior is not an issue against PR #202. Nothing significant changed for this in NFSRODS AFAIK. Perhaps the solution is due to the version change in Jargon.
```
$ ils -Ad /tempZone
/tempZone:
        ACL - g:public#tempZone:read_object   rods#tempZone:own
        Inheritance - Disabled
$ ils -Ad /tempZone/pl
/tempZone/pl:
        ACL - g:public#tempZone:read_object   rods#tempZone:own
        Inheritance - Disabled
$ ils -Ad /tempZone/pl/archive
/tempZone/pl/archive:
        ACL - g:public#tempZone:read_object   rods#tempZone:own
        Inheritance - Disabled
```

And here's the output of NFSRODS listing the contents of the collection.
```
$ sudo -u alice ls -l /mnt/nfsrods/pl/archive
total 0
d--x------ 1 nobody nogroup 0 May 20 18:15 col0
d--x------ 1 nobody nogroup 0 May 20 18:15 col1
```

**Comment by korydraughn** [comment]
I've also confirmed the issue happens in 2.2.0 and 2.1.0.
