### ISSUE TITLE
Add connection pooling/caching options

### ISSUE THREAD

**Issue by korydraughn** [irods/irods_client_nfsrods#74]
Feature branch containing stubs: https://github.com/korydraughn/irods_client_nfsrods/blob/dcbbf1cc8092aac8bab7ba615980859835606731/irods-vfs-impl/src/main/java/org/irods/nfsrods/vfs/ServerMain.java#L171-L179

**Comment by michael-conway** [comment]
Perfect...I'll put in the cache bootstrapping and we can start testing!

**Comment by korydraughn** [comment]
This was handled by https://github.com/irods/irods_client_nfsrods/commit/e50c25fe232c9b97429a178d615d8eade661a000.

Closing.
