### ISSUE TITLE
Issue running ls in a directory with a large number of files

### ISSUE THREAD

**Issue by darthtux** [irods/irods_client_nfsrods#77]
In irods I have a directory with 1001 sub-directories inside it.  I can use ils to correctly list the contents of this directory, but if I try try to run ls through an nfs mount only the first 99 directories are listed and each directory is listed 6 times.  Here is a the error message and the first 6 lines from the ls output.  

    -bash-4.2$ ls
    [ 1477.278142] NFS: directory darthtux/test contains a readdir loop.Please contact your server    vendor.  The file: 1 has duplicate cookie 124
    [ 1477.646263] NFS: directory darthtux/test contains a readdir loop.Please contact your server vendor.  The file: 1 has duplicate cookie 124
    [ 1477.702724] NFS: directory darthtux/test contains a readdir loop.Please contact your server vendor.  The file: 1 has duplicate cookie 124
    ls: reading directory .: Too many levels of symbolic links
    1    11  17  21  27  31  37  41  47  51  57  61  67  71  77  81  87  91  97
    1    12  17  22  27  32  37  42  47  52  57  62  67  72  77  82  87  92  97
    1    12  17  22  27  32  37  42  47  52  57  62  67  72  77  82  87  92  97
    1    12  17  22  27  32  37  42  47  52  57  62  67  72  77  82  87  92  97
    1    12  18  22  28  32  38  42  48  52  58  62  68  72  78  82  88  92  98
    1    12  18  22  28  32  38  42  48  52  58  62  68  72  78  82  88  92  98

The sub-directories in this folder are numbered 1 to 1001, so each of those numbers is a directory.  

I am running version 0.9.3 of irods_client_nfsrods.  

Here is my server.json file
    
    "nfs_server": {
        "port": 2049,
        "irods_mount_point": "/msi",
        "user_information_refresh_time_in_milliseconds": 3600000,
        "file_information_refresh_time_in_milliseconds": 1000,
        "user_access_refresh_time_in_milliseconds": 1000
    },

    "irods_client": {
        "zone": "msi",
        "host": "echo-irods.msi.umn.edu",
        "port": 1247,
        "default_resource": "storage",
        "ssl_negotiation_policy": "CS_NEG_REFUSE",
        "connection_timeout_in_seconds": 600,
        "proxy_admin_account": {
            "username": "rods",
            "password": "[REDACTED]"
        }
    }

Here are the options I have for the nfs mount.  

    echo-irods.msi.umn.edu:/ on /nfs type nfs4   (rw,relatime,vers=4.1,rsize=1048576,wsize=1048576,namlen=255,hard,proto=tcp,timeo=600,retrans=2,sec=sys,clientaddr=10.31.61.6,lookupcache=none,local_lock=none,addr=10.31.61.4)

Other possibly helpful notes.  Running ls on the nfs mount takes over 1 minute to return.  This is a demo instance with the irods server running the iCAT service, a postgresql database, and the irods client nfsrods in a docker container.  The machine has a quad core processor with 64Gigs of memory and an nvme for the postgres database.

**Comment by michael-conway** [comment]
Sounds like the offset is being set as 0 on paging each time?

**Comment by korydraughn** [comment]
This appears to be an issue with the kernel according to these stackoverflow posts:
- https://serverfault.com/questions/405565/nfsv4-too-many-levels-of-symbolic-links-error
- https://superuser.com/questions/599498/nfs-too-many-levels-of-symbolic-links-how-to-find-and-fix

@michael-conway Maybe, but I feel it is something outside of NFSRODS control.  The cookies for listing collections are the inode numbers which will be unique for every path.  inode numbers are recycled, but in my testing I was able to reproduce some of this behavior without making NFSRODS reuse inode numbers.

@darthtux What OS and iRODS version are you running?

**Comment by darthtux** [comment]
@korydraughn I am running a fully patched Centos7 machine with iRODS version 4.2.7.  

I also believe its an irods nfs client issue.  I have another directory with a similar number of files.  It is being served through straight nfsv4 with no iRODS at all.  It works as expected.  I wanted to see what the performance hit was like if I moved the contents to iRODS and exported them through the irods nfs client.  After doing so I ran into the same NFS errors and multiple listings of the same file.

**Comment by korydraughn** [comment]
Interesting. Are you passing any special options when mounting?  I saw you posted the options, but I want to know what your mount invocation looks like so that we can reproduce what you are seeing as much as possible.

**Comment by darthtux** [comment]
I just noticed something.  I was reviewing the requirements for running irods nfs client and noticed I had an older version of Docker.  I uninstalled it and installed the latest version from the official docker repo (19.03.6-3) and the behavior has changed.  So far I have let the ls run for about 30 minutes with out returning and this error is repeatedly logged to dmesg: 

    [337262.819367] NFS: directory darthtux/test contains a readdir loop.Please contact your server vendor.  The file: 1 has duplicate cookie 117

I have tried several different variations of mounting options but this is the set I currently have in fstab:
    echo-irods.msi.umn.edu:/	/nfs	nfs4	rw,relatime,vers=4.1,hard,proto=tcp,retrans=2,sec=sys,lookupcache=none,local_lock=none 0 0

**Comment by korydraughn** [comment]
Yes. I am seeing the same thing occasionally. I'm also seeing lots of `ls: cannot access 'dir_name': Remote I/O error` messages. My mount options look mostly identical to yours so I think we are good with the mount command.

It is possible that there is a bug in the NFS library we are using, but I'm beginning to think it is the issue mentioned in the posts I referenced earlier.

I'm pretty sure I hit an infinite loop when I passed `lookupcache=none`. I had to interrupt the operation to stop it.

**Comment by darthtux** [comment]
Thanks, removing `lookupcache=none` has my ls returning again.  Also the files are only listing 4 times each instead of the original 6.

**Comment by korydraughn** [comment]
I encounter infinite loops when not using `lookupcache=none` as well.  The following article makes me think the hash value of the cookie is colliding with previous values which ultimately lead to the infinite loop. See the following for more details:  https://lwn.net/Articles/544520/

**Comment by darthtux** [comment]
That article is really interesting but I'm not sure that is the issue.  I have two resources in iRODS right now.  The first points to an xfs file system and the second points to a Panasas volume, which is a proprietary filesystem.
