### ISSUE TITLE
LDAP support to NFSRODS

### ISSUE THREAD

**Issue by ac55-sanger** [irods/irods_client_nfsrods#80]
At present /etc/passwd is expected to contain all of the users planning to use NFSRODS. The users defined in this file MUST be defined in iRODS as well. Their usernames must match the names defined in this file exactly as this is how NFSRODS matches users to the correct account in iRODS.

It'll be good to have a direct LDAP support, so we don't need to add each user to /etc/passwd file.

**Comment by trel** [comment]
This is addressed in https://github.com/irods/irods_client_nfsrods/pull/47 and should be merged very soon - available in the next release.
