### ISSUE TITLE
md5sum command fails on a file under NFSRODS mounted directory

### ISSUE THREAD

**Issue by ac55-sanger** [irods/irods_client_nfsrods#88]
md5sum command throw I/O errors when running on a file under NFSRODS mounted directory.

server.json:
```
{
    "nfs_server": {
        "port": 2049,
        "irods_mount_point": "<zone_name>",
        "user_information_refresh_time_in_milliseconds": 3600000,
        "file_information_refresh_time_in_milliseconds": 1000,
        "user_access_refresh_time_in_milliseconds": 1000
    },

    "irods_client": {
        "zone": "<zone_name>",
        "host": "<zone_master_IES>",
        "port": 1247,
        "default_resource": "demoResc",
        "ssl_negotiation_policy": "CS_NEG_REFUSE",
        "connection_timeout_in_seconds": 600,
        "proxy_admin_account": {
            "username": "<username>",
            "password": "<password>"
        }
    }
}
```

Mounted directory: `/mnt/mount`

```
ac55@seq-dev-nfsrods-server:/mnt/mount/home/ac55$ md5sum hs38DH.fa
md5sum: hs38DH.fa: Input/output error
```

But this doesn't seem to happen with a "samtools view" command: 

```
ac55@seq-dev-nfsrods-server:/mnt/mount/home/ac55$ samtools view  EGAN00002215549.cram -T ~/hs38DH.fa| less -S
```
Reporting it to keep track of it.

**Comment by korydraughn** [comment]
this worked for me.  im running Ubuntu 16 and the tip of master.

can you post your OS version and NFSRODS build info?
you can get the NFSRODS info by typing: `docker run --rm nfsrods sha`

the log messages would be very helpful as well.

**Comment by ac55-sanger** [comment]
Here is the NFSRODS build info:

`Build Time    => 2020-04-07T09:54:35+0000
Build Version => 0.9.4
Build SHA     => cee670813167d253702c71f4517bd302af5db34f`

I'm running Ubuntu 18.04.4 LTS (Bionic Beaver).

This is strange. I checked again and it seemed to be working fine as well. Actually our user had reported this. I will cross-check with them again.

**Comment by ac55-sanger** [comment]
User confirmed it's working fine now. I shall close this ticket.

**Comment by trel** [comment]
Thanks.  Very strange.  If it happens again, please check the NFSRODS log for any details about why it was unhappy.

**Comment by ac55-sanger** [comment]
Will do. Thanks!
