### ISSUE TITLE
Add test cases

### ISSUE THREAD

**Issue by amieczko** [irods/irods_client_nfsrods#9]

**Comment by korydraughn** [comment]
SHA's containing work:

b4a31e1f5fec10a305e9c9bccfba737d263ebb00
402a25acecd5d556c7e8cb01eb1574e5b3e2a587
3164921342842601f726629f8e103694bafec76a
859c5e8ded64414ca0e567cd053267dbc625f0f7
32e26f8e857ec41d38ba5e5a168bf51e9193d9b0
e28d085d5102745fc63a7225c8f04029e8be835e
db150bd8c2a3fdfb59e9dbdb86f27a846c9544f8
